apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+tAtQMgFxPqrTKdkUhe7p1yTfhdVI2m2,iv:XIcuXucC/o1gK0TMQPuZxWB3jFI7LLlK6F7CXuedERA=,tag:236RNgNthTpinGUUmbPVCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age176r0elznjlnz3w2s3cf4ux98hph4ynqcyfanycxnd8w46g0e5ppstsw8h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOS9Xd2E3KzhvMmpoMXo3
            VHJEcUdQTnFlZmhSUHUzVmh4TXFDLzNBeDNBCkhBQzg3SVdhNjYzSG9sTXVOMjZG
            WWkzUWI5ek1UWmZkMFh4MnhxL0dwc1EKLS0tIDFtTmQwWXpPMzBNMWRQbGJjK2h6
            Tzh1NnRvdWxGYURDb09OUzVCc01XVDAKEf8u4ka8AqzY+kY3tSuG13kKrPhOym81
            Wa/8c4+AMIezWfHC+frEbUGyOGNiewr9+Ib1WCjFu3vrCiqlRf6MMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T03:54:53Z"
    mac: ENC[AES256_GCM,data:MFPjHa7l4xkVdBk/hxZZIaiFdFfuMyHWRDI8PQiRvnkAKMsLThxUlCfaARKPnj1z3sNf4d0eS1eMvcm91gnax6PcmpyMyzcGBM5I2oSElho/TrHymBOtYNjldOIEPmMX0GcWtWhabp9r1nRpg9E27lrJSK4cS5mZ4Vbcnnm9E7I=,iv:5mwhPEF24WiPTt1qF75DlEJXkijPC5WU2D2q1BK6R3c=,tag:yk6R94rmR/g+W2VqPWyDhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
