apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Wsl6IUlDZQDMPhWALUVwETzNXwdN98+2kq0n1LQwmnfyXW9Y39hEEQ==,iv:+hWFSL2VjdP2Vvp2xYOE73RRcvF1ogySibiawpXLTX0=,tag:CUQbal90so4yKahAjGkIHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age176r0elznjlnz3w2s3cf4ux98hph4ynqcyfanycxnd8w46g0e5ppstsw8h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUjdFdEtBbUp3UW1kWXB1
            N2Z6SHYya3RKeCtHbHBnY1hXYnRmbnI1YncwCnBKSXZxRUFrQ2FvN1E2UXRxcmRV
            Mm44TU5sU09QSnM0dmdkczJkeXdzNFUKLS0tIEFDc2xaeTA1NTc2QmJUSEU4bTh5
            N2h2N0ZPSlZNSEc1aG1pbXdRcjBUeTgKJTiJMamg6YVy3Im8SqtLkgZ3GXahiP2M
            Ti93JlBnWaa0UZrGgC/YoPn/B+NMEnpN4hHaVGTx7BXUnJ4SobmIaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T03:54:53Z"
    mac: ENC[AES256_GCM,data:age1Z0/0Sb592t6pCmtJOPG3Dj6QQddDdvrVsATF0CXUnf+LZSDOjszaZOUBi5FR41ngX1b5eu661DA0eT6t2YSVYphg8imrA8h1R8Lg2Uhcj8nJ6uypUWgSLFBn5wMN44TiWWTZwrdUO6Az3wyUsZireia/x9VMdl+vQBE8ue0=,iv:Q/5NDOMjPNfcsO3DgrUbL9HTeNqiYCI9fnAPQqo8Ii8=,tag:40/FJSSjvfloN/bquOtlpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
